// React/react_staging/04_GithubSearch_src/components/Search/Search.jsx
import React,{Component} from 'react'
import axios from 'axios'

export default class Search extends Component{

    savekeyWord = (event) => {
      let keyWord = event.target.value;
      this.setState({keyWord})      
    }

    searchUsers = () => {
      this.props.updateAppState({users:[],isFirst:false,isLoading:true,isError:false,error:null})
      let {keyWord} = this.state;
      //axios
      axios.get(`/api1/search/users?q=${keyWord}`).then(
        response => {
          let users = [];
          response.data.items.forEach(item => {
            let user = {name:item.login,href:item.html_url,imgSrc:item.avatar_url}
            users.push(user)
          })
          this.props.updateAppState({users:users,isFirst:false,isLoading:false,isError:false,error:null})
        },
        error => {
          this.props.updateAppState({users:[],isFirst:false,isLoading:false,isError:true,error:error.message})
        }
      )
    }

    render(){
        return (
            <section className="jumbotron">
            <h3 className="jumbotron-heading">Search Github Users</h3>
            <div>
              <input onChange={this.savekeyWord} type="text" placeholder="enter the name you search"/>&nbsp;
              <button onClick={this.searchUsers}>Search</button>
            </div>
          </section>
        )
    }
}

// Vue/vue2/src/vue_demo/05GitHubSearchWithAxios/components/Search.vue
<template>
  <div class="add-main">
    <span>请输入关键字查询：</span><input type="text" v-model="name" @keyup.13="search(name)">
  </div>
</template>

<script>
import PubSub from 'pubsub-js'
import axios from 'axios'

export default {
  name: 'Search',
  data () {
    return {
      name: ''
    }
  },
  methods: {
    search(name){
      PubSub.publish('show',{users:[],isFirst:false,isLoading:true,isError:false,error:null})

      axios.get(`https://api.github.com/search/users?q=${name}`).then(
        response => {
          let users = [];
          response.data.items.forEach(item => {
            let user = {name:item.login,href:item.html_url,imgSrc:item.avatar_url}
            users.push(user)
          })
          PubSub.publish('show',{users:users,isFirst:false,isLoading:false,isError:false,error:null})
        },
        error => {
          PubSub.publish('show',{users:[],isFirst:false,isLoading:false,isError:true,error:error.message})
        }
      )
    }

  },  
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>
